### PR TITLE
Fix compression of *os.Files.

### LINKED ISSUE #194: [bug] COmpressHandler is broken
Everything was working till yesterday. it starts failing today. I am using the google cloud build , so it takes the latest mux from repo. Local mux which is old is working fine.

I am using the compress handler like this

http.ListenAndServe(":8080", handlers.CompressHandler(r))

and serving static files.

but all the browser are not able to read the content. I tested with Mozzila , chrome and Microsoft EDGE.

Following error is shown 

image

When I use without compress , things works but now my server slow without compression

http.ListenAndServe(":8080",r)

### PR DESCRIPTION
**Pull request by muirdm**
After using httpsnoop to preserve interfaces, the compress response
writer now implemented ReaderFrom. ReaderFrom is used by net/http to
use sendfile when serving *os.Files. This breaks compression because
it serves directly to the underlying response writer, skipping the
compressor. Fix by implementing ReadFrom on our resposne writer to
copy to our compressor.

Fixes #194.

### CODE REVIEW

File: compress_test.go [hunk 1]
```diff
@@ -158,6 +164,54 @@ func TestCompressHandlerGzipDeflate(t *testing.T) {
 	}
 }
 
+// Make sure we can compress and serve an *os.File properly. We need
+// to use a real http server to trigger the net/http sendfile special
+// case.
+func TestCompressFile(t *testing.T) {
```
Comment (elithrar) [inline compress_test.go:170]: 👏🏻👏🏻👏🏻

**Comment by andig** [comment]
> After using httpsnoop to preserve interfaces, the compress response writer now implemented ReaderFrom.

Seems, after reading through the httpsnoop README, that using it is not as straightforward as advertised ;) Thank you for the quick turn-around time!
