### PR TITLE
Use httpsnoop to wrap ResponseWriter.

### LINKED ISSUE #169: [bug] Panic on nil Hijack interface due to compress handler
**Describe the bug**

The compress handler leaves an empty http.Hijacker interface in the wrapped response writer even when the incoming response writer does not implement http.Hijacker. This causes the wrapped response writer to still implement http.Hijacker, but if you try to call `Hijack()` it will panic.

**Steps to Reproduce**

```go
type myWriter struct {
	http.ResponseWriter
}

func main() {
	http.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		if h, ok := w.(http.Hijacker); ok {
			h.Hijack()
		}
	})

	myMiddleware := func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			h.ServeHTTP(&myWriter{w}, r)
		})
	}

	handler := myMiddleware(handlers.CompressHandler(http.DefaultServeMux))

	go func() {
		log.Panic(http.ListenAndServe("127.0.0.1:1337", handler))
	}()

	time.Sleep(1 * time.Second)

	http.Get("http://127.0.0.1:1337/test")
}
```

### PR DESCRIPTION
**Pull request by muirdm**
Wrapping http.ResponseWriter is fraught with danger. Our compress
handler made sure to implement all the optional ResponseWriter
interfaces, but that made it implement them even if the underlying
writer did not. For example, if the underlying ResponseWriter was
_not_ an http.Hijacker, the compress writer nonetheless appeared to
implement http.Hijacker, but would panic if you called Hijack().

On the other hand, the logging handler checked for certain
combinations of optional interfaces and only implemented them as
appropriate. However, it didn't check for all optional interfaces or
all combinations, so most optional interfaces would still get lost.

Fix both problems by using httpsnoop to do the wrapping. It uses code
generation to ensure correctness, and it handles std lib changes like
the http.Pusher addition in Go 1.8.

Fixes #169.

### CODE REVIEW

File: compress_test.go [hunk 1]
```diff
@@ -220,3 +215,32 @@ func TestCompressHandlerPreserveInterfaces(t *testing.T) {
 	r.Header.Set(acceptEncoding, "deflate")
 	h.ServeHTTP(rw, r)
 }
+
+type paltryResponseWriter struct{}
```
Comment (elithrar) [inline compress_test.go:219]: Ha.

**Comment by elithrar** [comment]
Thanks very much, @muirdm!
